use_frameworks!

target 'DXCNetWorking_Example' do
  pod 'DXCNetWorking', :path => '../'

  target 'DXCNetWorking_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
